### ISSUE TITLE
Java: Problem while subscribing for data of thermometer

### ISSUE THREAD

**Issue by ramogundogdu** [relayr/java-sdk#1]
I use the java examples for the thermometer from [hier](https://github.com/relayr/java-sdk-example) with java-sdk-1.0.5-SNAPSHOT.jar I can't receive the thermometer data. How can I solve the problem?

The Output:

1 TRANSMITTERS
My Wunderbar
1 GROUPS
My Wunderbar Master Module
Find thermometer
8 DEVICES
light
gyroscope
New Device
thermometer
microphone
New Device
infrared
bridge
Subscribe to readings using model.
Problem while subscribing for data

```
java.util.concurrent.TimeoutException
    at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.onTimeout(OperatorTimeoutBase.java:169)
    at rx.internal.operators.OperatorTimeout$1$1.call(OperatorTimeout.java:42)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by bernardpletikosa** [comment]
Hi ramogundogdu!

Firstly, I updated the example, so please use the new code, because there are more explanations and it uses the newer version of Java-SDK.

Secondly, looking at the logs, it seems like you did everything right but subscribing to device data timed out. That means that there was no data received from your wunderbar's thermometer in 5 seconds.

P.S. I just tried with my wunderbar and everything worked.

Best,
Bernard

**Comment by ramogundogdu** [comment]
Thank @bernardpletikosa for the update. Now I use updated examples with the new SDK version 1.1.0. It happens to me what strange: When I run my Example my Wunderdar stops to send data. I can not explain this. What might be the reason?

**Comment by bernardpletikosa** [comment]
Hi @ramogundogdu!
Example is not in any way directly connected to the Wunderbar. It only shows the live data if there is any.

First, you need to be sure that your wunderbar is sending data to the cloud. 
If you can't see the data on web dashboard or android dashboard app check this [https://developer.relayr.io/documents/WunderBar/MM](documentation) for detailed explanation.

**Comment by ramogundogdu** [comment]
The master module first sends the sensor data. I am sure in this case. As soon I run the  Java sampleproject it stops to send the data to the cloud. I can see the data sending by stopping of led flashing of the master module. That happens only when I run the sample project. Is that not strange?

**Comment by bernardpletikosa** [comment]
It seems like it was some temporary issue not related to the SDK.
